# Generated by Django 5.0.7 on 2024-08-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_student_index_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
