# Generated by Django 5.0.7 on 2024-08-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0007_alter_profile_user_type_teacher_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
